/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin <your.name at your.org>
 */
public class Admin2 extends javax.swing.JFrame {

    /**
     * Creates new form Admin3
     */
    public Admin2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flatButton = new javax.swing.JButton();
        maintenanceButton = new javax.swing.JButton();
        ownerButton = new javax.swing.JButton();
        rentalButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flatButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\flatDetails.png")); // NOI18N
        flatButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flatButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                flatButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                flatButtonMouseExited(evt);
            }
        });
        getContentPane().add(flatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 310, 170));

        maintenanceButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\maintenanceInfo.png")); // NOI18N
        maintenanceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maintenanceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maintenanceButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maintenanceButtonMouseExited(evt);
            }
        });
        getContentPane().add(maintenanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 310, 170));

        ownerButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\totalOwners.png")); // NOI18N
        ownerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ownerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ownerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ownerButtonMouseExited(evt);
            }
        });
        getContentPane().add(ownerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 310, 170));

        rentalButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\totalRentals.png")); // NOI18N
        rentalButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rentalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rentalButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rentalButtonMouseExited(evt);
            }
        });
        getContentPane().add(rentalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 450, 310, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\admin3.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flatButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flatButtonMouseEntered
        // TODO add your handling code here:
        flatButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\flatDetails_1.png"));
    }//GEN-LAST:event_flatButtonMouseEntered

    private void flatButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flatButtonMouseExited
        // TODO add your handling code here:
        flatButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\flatDetails.png"));
    }//GEN-LAST:event_flatButtonMouseExited

    private void maintenanceButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintenanceButtonMouseEntered
        // TODO add your handling code here:
        maintenanceButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\maintenanceInfo_1.png"));
    }//GEN-LAST:event_maintenanceButtonMouseEntered

    private void maintenanceButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintenanceButtonMouseExited
        // TODO add your handling code here:
        maintenanceButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\maintenanceInfo.png"));
    }//GEN-LAST:event_maintenanceButtonMouseExited

    private void ownerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ownerButtonMouseEntered
        // TODO add your handling code here:
        ownerButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\totalOwners_1.png"));
    }//GEN-LAST:event_ownerButtonMouseEntered

    private void ownerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ownerButtonMouseExited
        // TODO add your handling code here:
        ownerButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\totalOwners.png"));
    }//GEN-LAST:event_ownerButtonMouseExited

    private void rentalButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentalButtonMouseEntered
        // TODO add your handling code here:
        rentalButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\totalRentals_1.png"));
    }//GEN-LAST:event_rentalButtonMouseEntered

    private void rentalButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentalButtonMouseExited
        // TODO add your handling code here:
        rentalButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\totalRentals.png"));
    }//GEN-LAST:event_rentalButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton flatButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton maintenanceButton;
    private javax.swing.JButton ownerButton;
    private javax.swing.JButton rentalButton;
    // End of variables declaration//GEN-END:variables
}
