
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin <your.name at your.org>
 */
public class Admin1 extends javax.swing.JFrame {

    /**
     * Creates new form Admin1
     */
    public Admin1() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flatButton = new javax.swing.JButton();
        maintenanceButton = new javax.swing.JButton();
        employeeButton = new javax.swing.JButton();
        complainButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flatButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\flatDetails.png")); // NOI18N
        flatButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flatButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                flatButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                flatButtonMouseExited(evt);
            }
        });
        flatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flatButtonActionPerformed(evt);
            }
        });
        getContentPane().add(flatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 310, 170));

        maintenanceButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\maintenanceInfo.png")); // NOI18N
        maintenanceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maintenanceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maintenanceButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maintenanceButtonMouseExited(evt);
            }
        });
        maintenanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(maintenanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 310, 170));

        employeeButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\UTKARSH SINGH GEHLOT\\OneDrive\\Desktop\\image\\Vivek\\totalEmployees.png")); // NOI18N
        employeeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeeButtonMouseExited(evt);
            }
        });
        employeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(employeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 310, 170));

        complainButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\complain_box.png")); // NOI18N
        complainButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        complainButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                complainButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                complainButtonMouseExited(evt);
            }
        });
        complainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complainButtonActionPerformed(evt);
            }
        });
        getContentPane().add(complainButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 450, 310, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\admin1.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flatButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flatButtonMouseEntered
        // TODO add your handling code here:
        flatButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\flatDetails_1.png"));
    }//GEN-LAST:event_flatButtonMouseEntered

    private void flatButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flatButtonMouseExited
        // TODO add your handling code here:
        flatButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\flatDetails.png"));
    }//GEN-LAST:event_flatButtonMouseExited

    private void maintenanceButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintenanceButtonMouseEntered
        // TODO add your handling code here:
        maintenanceButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\maintenanceInfo_1.png"));
    }//GEN-LAST:event_maintenanceButtonMouseEntered

    private void maintenanceButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintenanceButtonMouseExited
        // TODO add your handling code here:
        maintenanceButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\maintenanceInfo.png"));
    }//GEN-LAST:event_maintenanceButtonMouseExited

    private void employeeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeButtonMouseEntered
        // TODO add your handling code here:
        employeeButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\UTKARSH SINGH GEHLOT\\OneDrive\\Desktop\\image\\Vivek\\totalEmployees_1.png"));
    }//GEN-LAST:event_employeeButtonMouseEntered

    private void employeeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeButtonMouseExited
        // TODO add your handling code here:
        employeeButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\UTKARSH SINGH GEHLOT\\OneDrive\\Desktop\\image\\Vivek\\totalEmployees.png"));
    }//GEN-LAST:event_employeeButtonMouseExited

    private void complainButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complainButtonMouseEntered
        // TODO add your handling code here:
        complainButton.setIcon(new javax.swing.ImageIcon("D:/ApartmentManagementSystem/src/main/java/images/complain_box_1.png"));
    }//GEN-LAST:event_complainButtonMouseEntered

    private void complainButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complainButtonMouseExited
        // TODO add your handling code here:
        complainButton.setIcon(new javax.swing.ImageIcon("D:/ApartmentManagementSystem/src/main/java/images/complain_box.png"));
    }//GEN-LAST:event_complainButtonMouseExited

    private void flatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flatButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new editresidentsdetails().setVisible(true);
        
//        try {
//            editresidentsdetails obj = new editresidentsdetails();
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/projectdb", "root", "Utkarsh@20");
//            PreparedStatement pst = conn.prepareStatement("Select name, email , phone ,username from signup");
//            ResultSet rs = pst.executeQuery();
//            while (rs.next()) {
//                String name = rs.getString("name");
//                String usern = rs.getString("username");
//                String email = rs.getString("email");
//                String phon = rs.getString("phone");
//                
//                
//                
//                String dbView[] = {name, usern, email, phon};
//                DefaultTableModel dft = (DefaultTableModel)obj.jTable1.getModel();
//                
//                dft.addRow(dbView);
//            }
//            new editresidentsdetails().setVisible(true);
//        }
//        catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_flatButtonActionPerformed

    private void maintenanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new MaintenanceDashboard().setVisible(true);
        
    }//GEN-LAST:event_maintenanceButtonActionPerformed

    private void complainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complainButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ComplainDashboard().setVisible(true);
    }//GEN-LAST:event_complainButtonActionPerformed

    private void employeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new EmployeeDashboard().setVisible(true);
    }//GEN-LAST:event_employeeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton complainButton;
    private javax.swing.JButton employeeButton;
    private javax.swing.JButton flatButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton maintenanceButton;
    // End of variables declaration//GEN-END:variables
}
