/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
import java.sql.*;
import javax.swing.*;
import project.select;
public class LoginAsAdmin extends javax.swing.JFrame {

    /**
     * Creates new form LoginAsAdmin
     */
    public LoginAsAdmin() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }
    
    public boolean validate_login(String usern , String pass , String keyw){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/projectdb", "root", "Utkarsh@20");
            PreparedStatement pst = conn.prepareStatement("Select * from admindata where username = ? and password = ? and keyword = ?" );
            pst.setString(1,usern);
            pst.setString(2,pass);
            pst.setString(3,keyw);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                return true;
            }
            else{
                return false;
            }
            
            
            
        }
        catch(Exception e){
            e.printStackTrace();
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        keyword = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 220, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 120, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Keyword");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 120, 50));

        username.setBackground(new java.awt.Color(255, 204, 255));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 400, 30));

        keyword.setBackground(new java.awt.Color(255, 204, 255));
        keyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordActionPerformed(evt);
            }
        });
        getContentPane().add(keyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 400, 30));

        password.setBackground(new java.awt.Color(255, 204, 255));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 400, 30));

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\LOGIN AS ADMIN.png")); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 400, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\username.png")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\password.png")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\keyword.png")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\bg_1.png")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(username.getText().length() == 0){
            JOptionPane.showMessageDialog(null,"Enter username");
            setVisible(false);
            new Login().setVisible(true);}
        else if(password.getText().length()==0){
            JOptionPane.showMessageDialog(null,"Enter password");
            setVisible(false);
            new Login().setVisible(true);
        }
        else if(keyword.getText().length() == 0){
            JOptionPane.showMessageDialog(null,"Enter keyword");
            setVisible(false);
            new Login().setVisible(true);
        }
        else{
            String user = username.getText();
            String pwd = password.getText();
            String key = keyword.getText();
            if(validate_login(user,pwd,key)){
                    JOptionPane.showMessageDialog(null, "Login Sucessfull!!");
                    if (key.equals("president202")){
                        setVisible(false);
                        new Admin1().setVisible(true);
                    }
                    else if (key.equals("vicepresident301")){
                        setVisible(false);
                        new Admin2().setVisible(true);
                    }
                    else if (key.equals("treasurer201")){
                        setVisible(false);
                        new Admin3().setVisible(true);
                    }
                    else if (key.equals("member503")){
                        setVisible(false);
                        new Admin4().setVisible(true);
                    }
                    else if (key.equals("member101")){
                        setVisible(false);
                        new Admin5().setVisible(true);
                    }
                    
                }
            
//                JOptionPane.showMessageDialog(null, "Correct Login Credentials");}
            else{
                JOptionPane.showMessageDialog(null, "Incorrect Login Credentials");
                setVisible(false);
                new LoginAsAdmin().setVisible(true);
            }
        }
        
        
//        String user = username.getText();
//        String pass = password.getText();
//        String key = keyword.getText();
//        
//        if(user.equals("") || pass.equals("") || key.equals("")){
//            JOptionPane.showMessageDialog(null,"Every field is required");
//            setVisible(false);
//            new LoginAsAdmin().setVisible(true);
//        }
//        else{
//            try{
//                
//                ResultSet rs = select.getData("select username from admindata where password='"+pass+"'");
//                System.out.println(rs);
//                
//            }   
//            catch(Exception e){
//                JOptionPane.showMessageDialog(null, "Invalid Password");
//            }
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAsAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField keyword;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
