
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin <your.name at your.org>
 */
public class userDashboard extends javax.swing.JFrame {

    /**
     * Creates new form userDashboard
     */
    public userDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);       //center form in the screen
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workerDetailButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        maintenanceInfoButton = new javax.swing.JButton();
        User = new javax.swing.JLabel();
        TelecomButton = new javax.swing.JButton();
        committeeDetail = new javax.swing.JButton();
        complainButton = new javax.swing.JButton();
        userBg = new javax.swing.JLabel();
        userExtract = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workerDetailButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\contact.png")); // NOI18N
        workerDetailButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                workerDetailButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                workerDetailButtonMouseExited(evt);
            }
        });
        workerDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workerDetailButtonActionPerformed(evt);
            }
        });
        getContentPane().add(workerDetailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 310, 170));

        profileButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\profile.png")); // NOI18N
        profileButton.setBorder(new javax.swing.border.MatteBorder(null));
        profileButton.setBorderPainted(false);
        profileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileButtonMouseExited(evt);
            }
        });
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(profileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 310, 170));

        maintenanceInfoButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\maintenance_info.png")); // NOI18N
        maintenanceInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maintenanceInfoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maintenanceInfoButtonMouseExited(evt);
            }
        });
        maintenanceInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceInfoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(maintenanceInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, 310, 170));

        User.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 36)); // NOI18N
        getContentPane().add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 250, 40));

        TelecomButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\telecom_info.png")); // NOI18N
        TelecomButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TelecomButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TelecomButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TelecomButtonMouseExited(evt);
            }
        });
        TelecomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelecomButtonActionPerformed(evt);
            }
        });
        getContentPane().add(TelecomButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 310, 170));

        committeeDetail.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\committee_details.png")); // NOI18N
        committeeDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                committeeDetailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                committeeDetailMouseExited(evt);
            }
        });
        committeeDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                committeeDetailActionPerformed(evt);
            }
        });
        getContentPane().add(committeeDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 310, 170));

        complainButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\complain_box.png")); // NOI18N
        complainButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                complainButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                complainButtonMouseExited(evt);
            }
        });
        complainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complainButtonActionPerformed(evt);
            }
        });
        getContentPane().add(complainButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 490, 310, 170));

        userBg.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\userBg.png")); // NOI18N
        getContentPane().add(userBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        userExtract.setText("jLabel1");
        getContentPane().add(userExtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseEntered
        // TODO add your handling code here:
        profileButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\profile_1.png"));
    }//GEN-LAST:event_profileButtonMouseEntered

    private void profileButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseExited
        // TODO add your handling code here:
        profileButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\profile.png"));
    }//GEN-LAST:event_profileButtonMouseExited

    private void workerDetailButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerDetailButtonMouseEntered
        // TODO add your handling code here:
        workerDetailButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\contact_1.png"));
    }//GEN-LAST:event_workerDetailButtonMouseEntered

    private void workerDetailButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerDetailButtonMouseExited
        // TODO add your handling code here:
        workerDetailButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\contact.png"));
    }//GEN-LAST:event_workerDetailButtonMouseExited

    private void TelecomButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelecomButtonMouseEntered
        // TODO add your handling code here:
        TelecomButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\telecom_info_1.png"));
    }//GEN-LAST:event_TelecomButtonMouseEntered

    private void TelecomButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelecomButtonMouseExited
        // TODO add your handling code here:
        TelecomButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\telecom_info.png"));
    }//GEN-LAST:event_TelecomButtonMouseExited

    private void committeeDetailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_committeeDetailMouseEntered
        // TODO add your handling code here:
        committeeDetail.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\committee_details_1.png"));
    }//GEN-LAST:event_committeeDetailMouseEntered

    private void committeeDetailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_committeeDetailMouseExited
        // TODO add your handling code here:
        committeeDetail.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\committee_details.png"));
    }//GEN-LAST:event_committeeDetailMouseExited

    private void complainButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complainButtonMouseEntered
        // TODO add your handling code here:
        complainButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\complain_box_1.png"));
    }//GEN-LAST:event_complainButtonMouseEntered

    private void complainButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complainButtonMouseExited
        // TODO add your handling code here:
        complainButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\complain_box.png"));
    }//GEN-LAST:event_complainButtonMouseExited

    private void maintenanceInfoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintenanceInfoButtonMouseEntered
        // TODO add your handling code here:
        maintenanceInfoButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\maintenance_info_1.png"));
    }//GEN-LAST:event_maintenanceInfoButtonMouseEntered

    private void maintenanceInfoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintenanceInfoButtonMouseExited
        // TODO add your handling code here:
        maintenanceInfoButton.setIcon(new javax.swing.ImageIcon("D:\\ApartmentManagementSystem\\src\\main\\java\\images\\maintenance_info.png"));
    }//GEN-LAST:event_maintenanceInfoButtonMouseExited

    private void TelecomButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelecomButtonMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new telecomDetails().setVisible(true);
    }//GEN-LAST:event_TelecomButtonMouseClicked

    private void committeeDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_committeeDetailActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new committeeDetails().setVisible(true);
    }//GEN-LAST:event_committeeDetailActionPerformed

    private void workerDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workerDetailButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new workerDetails().setVisible(true);
    }//GEN-LAST:event_workerDetailButtonActionPerformed

    private void complainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complainButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        complainBox obj1 = new complainBox();
        String usercomp = userExtract.getText();
        obj1.UserandEmail(usercomp);
        obj1.setVisible(true);
        
    }//GEN-LAST:event_complainButtonActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false); // checkk
        profileInfo obj = new profileInfo();       
        Login obj2 = new Login();
        String user = userExtract.getText(); 
        obj.ShowProfile(user);
        obj.setVisible(true);
       
        
        
        
        
    }//GEN-LAST:event_profileButtonActionPerformed

    private void maintenanceInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceInfoButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Maintenance obj1 = new Maintenance();
        String username1 = userExtract.getText();
        obj1.ShowMaintenance(username1);
        obj1.setVisible(true);
        
        if ("0".equals(obj1.MaintenanceLabel.getText())){
            obj1.Status.setText("Your maintenance is up to date");
            obj1.pay.setEnabled(false);
        }
       
        
        
    }//GEN-LAST:event_maintenanceInfoButtonActionPerformed

    private void TelecomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelecomButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelecomButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TelecomButton;
    public javax.swing.JLabel User;
    private javax.swing.JButton committeeDetail;
    private javax.swing.JButton complainButton;
    private javax.swing.JButton maintenanceInfoButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JLabel userBg;
    public javax.swing.JLabel userExtract;
    private javax.swing.JButton workerDetailButton;
    // End of variables declaration//GEN-END:variables
}
